sonar.projectKey=cn.itcast.demo:mmorpg-parent
sonar.projectName=MyMmorpg
sonar.sourceEncoding=UTF-8
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml
sonar.exclusions=**/target/**,**/*Proto*.java,**/generated-sources/**
