server:
  type: 1
  port: 8080

admin:
  http:
    ips: 127.0.0.1

socket:
  id: 10001
  serverIp: ""
  port: 0

rpc:
  schedule:
    health-ms: 30000
    directory-sync-ms: 59000
  port: 0
  balanceStrategy: ROUND
  center:
    id: 999999
    ip: 127.0.0.1
    port: 8888
  signKey: ${RPC_SIGN_KEY:}

http:
  port: 0

webSocket:
  port: 0
